config:
  # macro 항목은 매크로방지를 위한 것입니다. id에 적혀있는 블럭을 깨면 command가 실행됩니다.
  # macro 항목에 적혀있는 아이템을 우클릭 할 경우, 기본 아이템인 돌로 해당 블럭이 바뀌게 됩니다. 
  macro:
    id: 89
    id2: 55
    command: "balance"
  Initial_Default:
    id: 1
    meta: 0
  Initial_SnowMountain:
    id: 79
    meta: 0



