config:
  macro:
    id: 89
    command: "balance"
  # 여기에 등록된 아이템은 creative 모드의 플레이어가 부순 블럭에도 관여합니다.
  #
  # 월드별로 따로 사용이 가능합니다.
  #
  # 인식시킬 블록은 '블록번호*메타' 형식으로 작성하시면 됩니다.
  #
  # replaceto 항목은 블럭이 부서졌을때 그자리에 생성될 블록의 목록입니다.
  # -'아이템:메타, 확률%' 과 같이 사용합니다.
  #
  # drop_itemMeta항목을 빈칸으로 두시면 원래 드랍템이 드랍됩니다.
  # -'아이템이름, 확률%'와 같이 사용합니다. 아이템이름은 item.yml에 적은것을 사용합니다.
  # 이 항목이 비어있을시 정상작동하지 않으니 꼭 채워주세요.
  #
  # dropexp 항목에 적은 정수만큼 경험치 구슬이 드랍됩니다.
  #
  # commands 항목에 적은 커맨드를 해당 블럭이 부서질때 실행합니다. 
  # 콘솔이 사용하지 못하는 커맨드는 사용 불가능 합니다.
  #
  # potion 항목에 적은 이펙트들을 블럭이 부서졌을때 부순사람에게 부여합니다.
  # - '이펙트번호, 레벨:시간'과 같이 사용합니다.
  #
  # macro 항목은 매크로방지를 위한 것입니다. id에 적혀있는 블럭을 깨면 command가 실행됩니다.
  # macro 항목에 적혀있는 아이템을 우클릭 할 경우, 기본 아이템인 돌로 해당 블럭이 바뀌게 됩니다. 
  #
  # delay 항목은 각 블럭당 재생성에 지연을 줍니다. 공식에서는 ms단위라고 쓰여있지만 사실상
  # 그렇지 못하므로 적절히 값을 키워 사용할 것을 권장합니다. 개발자의 PC에서는 100일때 5초가량 지연되었습니다.
  #
  # durability 항목은 해당 블록이 깨질때마다 떨어질 내구도의 수입니다.
  world:
    1*0:
      replaceto:
        - '1:0, 10%'
        - '3:0, 20%'
        - '4:0, 30%'
        - '35:8, 40%'
      dropexp: 20
      drop_itemMeta:
        - 'ex, 100%'
      commands:
        - ''
      potion:
        - '1, 1:10'
      delay: 100
      durability: 1
  world_nether:
  world_the_end: